imports:
  - { resource: ../common.yml }

services:
  ps_checkout.logger.file.finder:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerFileFinder'
    public: true
    arguments:
      - '@ps_checkout.logger.directory'
      - '@ps_checkout.logger.filename'

  ps_checkout.logger.file.reader:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerFileReader'
    public: true

  ps_checkout.env.segmentenv:
    class: 'PrestaShop\Module\PrestashopCheckout\Environment\SegmentEnv'
    public: true

  ps_checkout.segment.tracker:
    class: 'PrestaShop\Module\PrestashopCheckout\Segment\SegmentTracker'
    public: true
    arguments:
      - '@ps_checkout.env.segmentenv'
      - '@ps_checkout.manager.shopuuid'

  ps_checkout.repository.orderpayment:
    class: 'PrestaShop\Module\PrestashopCheckout\Repository\OrderPaymentRepository'
    public: true

  ps_checkout.repository.order:
    class: 'PrestaShop\Module\PrestashopCheckout\Repository\OrderRepository'
    public: true

  ps_checkout.presenter.order.pending:
    class: 'PrestaShop\Module\PrestashopCheckout\Presenter\Order\OrderPendingPresenter'
    public: true

  ps_checkout.presenter.transaction:
    class: 'PrestaShop\Module\PrestashopCheckout\Presenter\Transaction\TransactionPresenter'
    public: true

  ps_checkout.guzzle.client:
    class: 'GuzzleHttp\Client'
    public: true

  ps_checkout.cache.marketplace:
    class: 'Symfony\Component\Cache\Simple\FilesystemCache'
    public: true
    arguments:
      - 'marketplace'
      - 604800
      - '@=service("ps_checkout.cache.directory").getPath()'

  ps_checkout.marketplace.provider:
    class: 'PrestaShop\Module\PrestashopCheckout\MarketPlace\MarketPlaceModuleDataProvider'
    public: true
    arguments:
      - '@ps_checkout.guzzle.client'
      - '@ps_checkout.cache.marketplace'

  ps_checkout.marketplace.handler:
    class: 'PrestaShop\Module\PrestashopCheckout\MarketPlace\GetMarketPlaceModuleDataQueryHandler'
    public: true
    arguments:
      - '@ps_checkout.marketplace.provider'

  ps_checkout.marketplace.query:
    class: 'PrestaShop\Module\PrestashopCheckout\MarketPlace\GetMarketPlaceModuleDataQuery'
    public: true
    arguments:
      - '46347' # PrestaShop Addons module id
      - !php/const _PS_VERSION_
      - '@=service("ps_checkout.context.prestashop").getLanguage().language_code'
      - '@=service("ps_checkout.context.prestashop").getLanguage().iso_code'

  ps_checkout.marketplace.module_version_checker:
    class: 'PrestaShop\Module\PrestashopCheckout\MarketPlace\ModuleVersionChecker'
    public: true
    arguments:
      - '@ps_checkout.marketplace.handler'
      - '@ps_checkout.marketplace.query'
      - '@ps_checkout.module'
