services:
  _defaults:
    public: true

  ps_checkout.module:
    class: 'Ps_checkout'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'ps_checkout'

  ps_checkout.cache.directory:
    class: 'PrestaShop\Module\PrestashopCheckout\Cache\CacheDirectory'
    arguments:
      - !php/const _PS_VERSION_
      - !php/const _PS_ROOT_DIR_
      - !php/const _PS_MODE_DEV_

  ps_checkout.logger.directory:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerDirectory'
    arguments:
      - !php/const _PS_VERSION_
      - !php/const _PS_ROOT_DIR_

  ps_checkout.logger.factory:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerFactory'
    arguments:
      - '@ps_checkout.logger.directory'
      - '@ps_checkout.module'

  ps_checkout.logger:
    class: 'Psr\Log\LoggerInterface'
    factory: ['@ps_checkout.logger.factory', 'build']
    arguments:
      - '@ps_checkout.logger.directory'

  ps_checkout.env.sentry:
    class: 'PrestaShop\Module\PrestashopCheckout\Environment\SentryEnv'

  ps_checkout.logger.sentry.handler:
    class: 'PrestaShop\Module\PrestashopCheckout\Sentry\SentryHandler'
    arguments:
      - '@ps_checkout.env.sentry'

  ps_checkout.logger.sentry.processor:
    class: 'PrestaShop\Module\PrestashopCheckout\Sentry\SentryProcessor'
