services:
  _defaults:
    public: true

  ps_checkout.module:
    class: 'Ps_checkout'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'ps_checkout'

  ps_checkout.context.prestashop:
    class: 'PrestaShop\Module\PrestashopCheckout\Context\PrestaShopContext'

  ps_checkout.shop.provider:
    class: 'PrestaShop\Module\PrestashopCheckout\Shop\ShopProvider'

  ps_checkout.configuration.options.resolver:
    class: 'PrestaShop\Module\PrestashopCheckout\Configuration\PrestaShopConfigurationOptionsResolver'
    arguments:
      - '@=service("ps_checkout.shop.provider").getIdentifier()'

  ps_checkout.configuration:
    class: 'PrestaShop\Module\PrestashopCheckout\Configuration\PrestaShopConfiguration'
    arguments:
      - '@ps_checkout.configuration.options.resolver'

  ps_checkout.logger.directory:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerDirectory'
    arguments:
      - !php/const _PS_VERSION_
      - !php/const _PS_ROOT_DIR_

  ps_checkout.logger.filename:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerFilename'
    arguments:
      - '@=service("ps_checkout.module").name'
      - '@=service("ps_checkout.shop.provider").getIdentifier()'

  ps_checkout.logger.configuration:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerConfiguration'
    arguments:
      - '@ps_checkout.configuration'

  ps_checkout.env.sentry:
    class: 'PrestaShop\Module\PrestashopCheckout\Environment\SentryEnv'

  ps_checkout.logger.sentry.handler:
    class: 'PrestaShop\Module\PrestashopCheckout\Sentry\SentryHandler'
    arguments:
      - '@ps_checkout.env.sentry'

  ps_checkout.logger.handler.factory:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerHandlerFactory'
    arguments:
      - '@=service("ps_checkout.logger.directory").getPath()'
      - '@=service("ps_checkout.logger.filename").get()'
      - '@=service("ps_checkout.logger.configuration").getMaxFiles()'
      - '@=service("ps_checkout.logger.configuration").getLevel()'

  ps_checkout.logger.handler:
    class: 'Monolog\Handler\HandlerInterface'
    factory: ['@ps_checkout.logger.handler.factory', 'build']

  ps_checkout.logger.factory:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerFactory'
    arguments:
      - '@=service("ps_checkout.module").name'
      - '@ps_checkout.logger.handler'
      - '@ps_checkout.logger.sentry.handler'
      - '@ps_checkout.logger.sentry.processor'

  ps_checkout.logger:
    class: 'Psr\Log\LoggerInterface'
    factory: ['@ps_checkout.logger.factory', 'build']
    arguments:
      - '@ps_checkout.logger.directory'

  ps_checkout.logger.sentry.processor:
    class: 'PrestaShop\Module\PrestashopCheckout\Sentry\SentryProcessor'
    arguments:
      - '@ps_checkout.repository.prestashop.account'

  ps_checkout.paypal.configuration:
    class: 'PrestaShop\Module\PrestashopCheckout\PayPal\PayPalConfiguration'
    arguments:
      - '@ps_checkout.configuration'

  ps_checkout.persistent.configuration:
    class: 'PrestaShop\Module\PrestashopCheckout\PersistentConfiguration'
    arguments:
      - '@ps_checkout.configuration'

  ps_checkout.express_checkout.configuration:
    class: 'PrestaShop\Module\PrestashopCheckout\ExpressCheckout\ExpressCheckoutConfiguration'
    arguments:
      - '@ps_checkout.configuration'

  ps_checkout.api.firebase.auth:
    class: 'PrestaShop\Module\PrestashopCheckout\Api\Firebase\Auth'

  ps_checkout.api.firebase.auth.factory:
    class: 'PrestaShop\Module\PrestashopCheckout\Api\Firebase\AuthFactory'
    arguments:
      - '@ps_checkout.api.firebase.auth'
      - '@ps_checkout.persistent.configuration'

  ps_checkout.repository.paypal.account:
    class: 'PrestaShop\Module\PrestashopCheckout\Repository\PaypalAccountRepository'
    arguments:
      - '@ps_checkout.configuration'

  ps_checkout.sdk.paypal.linkbuilder:
    class: 'PrestaShop\Module\PrestashopCheckout\Builder\PayPalSdkLink\PayPalSdkLinkBuilder'
    arguments:
      - '@ps_checkout.repository.paypal.account'
      - '@ps_checkout.paypal.configuration'

  ps_checkout.repository.prestashop.account:
    class: 'PrestaShop\Module\PrestashopCheckout\Repository\PsAccountRepository'
    arguments:
      - '@ps_checkout.configuration'

  ps_checkout.store.module.psx:
    class: 'PrestaShop\Module\PrestashopCheckout\Presenter\Store\Modules\PsxModule'
    arguments:
      - '@ps_checkout.context.prestashop'
      - '@ps_checkout.repository.prestashop.account'

  ps_checkout.builder.payload.onboarding:
    class: 'PrestaShop\Module\PrestashopCheckout\Builder\Payload\OnboardingPayloadBuilder'
    arguments:
      - '@ps_checkout.repository.prestashop.account'
