services:
  ps_checkout.store.module.psx:
    class: 'PrestaShop\Module\PrestashopCheckout\Presenter\Store\Modules\PsxModule'
    public: true
    arguments:
      - '@ps_checkout.context.prestashop'
      - '@ps_checkout.repository.prestashop.account'

  ps_checkout.store.module.paypal:
    class: 'PrestaShop\Module\PrestashopCheckout\Presenter\Store\Modules\PaypalModule'
    public: true
    arguments:
      - '@ps_checkout.repository.paypal.account'

  ps_checkout.store.module.firebase:
    class: 'PrestaShop\Module\PrestashopCheckout\Presenter\Store\Modules\FirebaseModule'
    public: true
    arguments:
      - '@ps_checkout.configuration'
      - '@ps_checkout.api.firebase.token'

  ps_checkout.store.module.configuration:
    class: 'PrestaShop\Module\PrestashopCheckout\Presenter\Store\Modules\ConfigurationModule'
    public: true
    arguments:
      - '@ps_checkout.pay_in_4x.configuration'
      - '@ps_checkout.express_checkout.configuration'
      - '@ps_checkout.paypal.configuration'
      - '@ps_checkout.funding_source.provider'
      - '@ps_checkout.module'

  ps_checkout.store.module.context:
    class: 'PrestaShop\Module\PrestashopCheckout\Presenter\Store\Modules\ContextModule'
    public: true
    arguments:
      - '@=service("ps_checkout.module").name'
      - '@=service("ps_checkout.module").module_key'
      - '@ps_checkout.context.prestashop'
      - '@ps_checkout.paypal.configuration'
      - '@ps_checkout.step.live'
      - '@ps_checkout.step.value'
      - '@ps_checkout.translations.translations'
      - '@ps_checkout.context.shop'
      - '@ps_checkout.shop.provider'
      - '@ps_checkout.manager.shopuuid'
      - '@ps_checkout.adapter.link'

  ps_checkout.store.module.session:
    class: 'PrestaShop\Module\PrestashopCheckout\Presenter\Store\Modules\SessionModule'
    public: true
    arguments:
      - '@ps_checkout.onboarding.state.handler'
      - '@ps_checkout.cache.session'

  ps_checkout.store.store:
    class: 'PrestaShop\Module\PrestashopCheckout\Presenter\Store\StorePresenter'
    public: true
    arguments:
      - [ '@ps_checkout.store.module.context', '@ps_checkout.store.module.firebase', '@ps_checkout.store.module.paypal', '@ps_checkout.store.module.psx', '@ps_checkout.store.module.configuration', '@ps_checkout.store.module.session' ]

  ps_checkout.presenter.cart:
    class: 'PrestaShop\Module\PrestashopCheckout\Presenter\Cart\CartPresenter'
